default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: 127.0.0.1
  username: postgres
  password: postgres

development:
  <<: *default
  database: touch_rails_14_4_2024_development


test:
  <<: *default
  database: touch_rails_14_4_2024_test


production:
  <<: *default
  database: touch_rails_14_4_2024_production
  username: touch_rails_14_4_2024
  password: <%= ENV["TOUCH_RAILS_14_4_2024_DATABASE_PASSWORD"] %>
