default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: touch_rails_14_4_2024_development

test:
  <<: *default
  database: touch_rails_14_4_2024_test

production:
  <<: *default
  database: touch_rails_14_4_2024_development
  username: postgres
  password: postgres
